### ISSUE TITLE
Stworzenie komendy "populate", generującej testowe dane

### ISSUE THREAD

**Issue by mateuszskoczek** [Szade-Organization/BetterCalendar-API#35]
Trzeba przygotować komendę uruchamianą z manage.py, która będzie generowała testowe dane i insertowała je do bazy. Komenda powinna przyjmować opcje pozwalające na wpływanie na sposób generowania danych (np. --seed, --activities_count, coś w tym stylu).
Na tym etapie wystarczy możliwość uruchomienia tej komendy. Implementacja generowania danych jest tu: https://github.com/Szade-Organization/BetterCalendar-API/issues/37

**Comment by WojciechSzade** [comment]
Zrobione, ale bez przekazywania seedu. Nie wiem czy to przy naszym nowym podejściu wymagane?
