### ISSUE TITLE
Stworzenie skryptu uruchamiającego API (populate i runserver), modyfikacja Dockerfile

### ISSUE THREAD

**Issue by mateuszskoczek** [Szade-Organization/BetterCalendar-API#36]
Wymaga: https://github.com/Szade-Organization/BetterCalendar-API/issues/35

Trzeba stworzyć skrypt, który będzie uruchamiany przy starcie kontenera, który:
1. Sprawdzi, czy:
- zdefiniowana została zmienna środowiskowa np. GENERATE_TEST_DATA i czy jest ustawiona na true
- jest możliwe połączenie z bazą danych 
- _czy dane zostały już wcześniej wygenerowane (np. poprzez zmienną środowiskową lub sprawdzenie czy dane istnieją w bazie)_
2. Jeżeli tak, to uruchomi komendę python manage.py populate. Opcje można przekazać poprzez zmienną środowiskową np. POPULATE_ARGS. _(jeżeli sprawdzanie czy dane zostały wygenerowane odbywa się za pomocą zmiennej środowiskowej to po wykonaniu komendy należy ją zmodyfikować)_
3. Wywołuje komendę runserver

Do tego trzeba zmodyfikować Dockerfile'a, żeby uruchamiał ten skrypt zamiast runserver (CMD ['start.sh'])

**Comment by WojciechSzade** [comment]
Chyba jednak rezygnujemy z tego podejścia, na rzecz statycznego przygotowania danych przy użyciu skryptu populate i wyeksportowania ich do skryptu js'owego uruchamianego razem z bazą?

**Comment by szmurlor** [comment]
Czy ja dobrze rozumiem, Wojtku, że chcesz przenieść to zadanie 'bootstrapowania' bazy danych z django migrate do JSa?
