### ISSUE TITLE
Implementacja generowania danych testowych (populate)

### ISSUE THREAD

**Issue by mateuszskoczek** [Szade-Organization/BetterCalendar-API#37]
Wymaga: https://github.com/Szade-Organization/BetterCalendar-API/issues/35

Właściwie dalszy ciąg issue 35. Należy dodać generowanie danych testowych i insertowanie ich do bazy.

**Comment by WojciechSzade** [comment]
Gotowe z całkiem sensownymi danymi, stworzonymi w kolaboracji z Fakerem i GPT.

**Comment by szmurlor** [comment]
Błagam, nie kolaboruj z Fakerem tylko współpracuj, albo wykorzystuj, lub twórz "przy pomocy" :-) Język polski jest piękny! :-)

**Comment by WojciechSzade** [comment]
> Błagam, nie kolaboruj z Fakerem tylko współpracuj, albo wykorzystuj, lub twórz "przy pomocy" :-) Język polski jest piękny! :-)

Też uważam, że jest piękny. Dlatego użyłem staropolskiego kolaboruj w znaczeniu właśnie - współpracuj :)
