### ISSUE TITLE
Stworzyć autentykację

### ISSUE THREAD

**Issue by WojciechSzade** [Szade-Organization/BetterCalendar-API#61]
Wybraliśmy django-rest-knox.

**Comment by WojciechSzade** [comment]
Zajmę się implementacją, ale do przemyślenia:  
- Jako metody autoryzacji na pewno dajemy knox'owy token, ale poza tym chyba po prostu basic user:password, po którym taki token dostajemy,  
- Jaki czas wygasania tokena? Domyślnie jest 10h, mi się wydaje okej,  
- Czy przedłużamy wygaśnięcie tokena po użyciu go? Moim zdaniem tak dla wygody użytkownika,  
- Czy potrzebujemy jakiś roli z określonymi poziomami permisji? Wydaje mi się, że wystarczy nam zwyczajny user i administrator i zapytania administracyjne się po prostu wydzieli,  
- Jakie dane zbieramy zakładając konto? Wiadomo, że email i hasło, ale robimy imię i nazwisko? Username osobno, czy sami tworzymy z imienia i nazwiska/email jako username?,  
- Reset hasła to po prostu mail?,  
- W przyszłości może dodamy 2FA? Ale na pewno nie teraz.

**Comment by achilinski** [comment]
-username/haslo
-Czas wygasania 72h, ale refresh token do przemyślenia, przedłużany po logowaniu
-2 role(admin i user)
-dane: username, email, hasło
-reset hasła email
-może ale najpierw google
