### ISSUE TITLE
Zmienić bazę danych na MongoDB

### ISSUE THREAD

**Issue by WojciechSzade** [Szade-Organization/BetterCalendar-API#8]
Należy sprawdzić dostępne metody integracji Django z MongoDB i wybrać najlepszą.
Zależy nam na możliwie wysokiej integracji z Django  - najlepiej żeby można było korzystać z wbudowanych metod.
Z tego co widziałem to Djongo oferuje takie rozwiązanie, ale trzeba zrobić lepszy research.
Następnie należy postawić lokalnie bazę i zintegrować ja z projektem. Bazę testową chyba wrzucamy bezpośrednio do repo chyba?

**Comment by achilinski** [comment]
Można użyć MongoDB atlas jest 5gb za darmo i nie będzie trzeba trzymać w repo, później można zmienić na azure czy coś innego

**Comment by mateuszskoczek** [comment]
Na razie postawiłem Atlasa, ale proponowałbym raczej postawić jakiegoś "deva" na jakiejś maszynie wirtualnej i na niej postawić instancję mongo + zdeployowany z masterów najnowszy frontend i backend. Albo coś w tym stylu. Maszyna na Azure może nam szybko zjeść fundusze, więc trzebaby poszukać jakichś alternatyw. Ja mam w domu serwer i stałe ip, więc mógłbym to ewentualnie to hostować u siebie, ale wolałbym tego uniknąć. Może politechnika udostępnia do takich projektów jakieś serwery, ale mocno w to wątpie.

W kązdym razie connection string do atlasa wygląda tak: mongodb+srv://<username>:<password>@bettercalendar.ov2aeb6.mongodb.net/bettercalendar?retryWrites=true&w=majority

Żeby się zalogować, musicie mieć login i hasło oraz muszę odblokować wasze adresy ip w panelu administracyjnym.
Stworzyłem na razie konta osobom z części backendowej zespołu oraz jedno "wspólne", głównie z myślą o ewentualnym ogólnodostępnym dla zespołu środowiskiem testowym.

Nie wiem jak to rozwiążemy, ja proponuje, żebyście mi podesłali swoje ip (publiczne np. stąd https://www.whatismyip.com/ dla każdej lokalizacji z której chcecie się łączyć z bazą) np. na priv na discord, a ja wam wyślę dane do logowania. Ewentualnie możemy wszyscy korzystać z tego jednego "wspólnego" konta, ale wtedy i tak musicie mi wysłać ip. Trzecia alternatywa jest taka, że po prostu postawimy sobie wszyscy lokalne instancje Mongo i będziemy na nich pracować, ale to raczej średnia opcja.

Po wprowadzeniu zmian w modelu trzeba odpalić dwie komendy (w sumie nie wiem czy dotyczy to każdej zmiany w modelu czy tylko przy dodawaniu nowych kolekcji, ale ja odpalałem po każdej zmianie):
python manage.py makemigrations API
python manage.py migrate

Wrzuciłem PRa do repo z opisem zmian w kodzie (jakbyście chcieli przejrzeć), ale tam jest jeszcze jedna rzecz do dodania (zostawiłem to sobie na jutro), więc na razie jest draft. Jak ktoś ma jakieś propozycje to możecie pisać.

https://github.com/Szade-Organization/BetterCalendar-API/pull/26

**Comment by WojciechSzade** [comment]
A tak właściwie, to nie można na potrzeby developerskie postawić bazy lokalnie i wrzucić jej do repozytorium?
Z adresami IP będzie taki problem, że chyba większość nie ma przypisanego stałego adresu IP.
A jak nie można do repozytorium, to przygotowany docker, ew. jak się nie da maszyna wirtualna?
Bo jak dla mnie na nasze potrzeby deweloperskie robienie tego ze zdalna bazą jest trochę bez sensu i będzie tylko generować problemy.
Na potrzeby produkcji oczywiście coś takiego się ogarnie.

**Comment by mateuszskoczek** [comment]
Co do adresów ip to jednak nieaktualne bo ustawiłem po prostu dostęp dla wszystkich adresów ip, więc z tym nie będzie problemu.
Jeszcze poprawka w connection stringu: mongodb+srv://username:password@bettercalendar.ov2aeb6.mongodb.net/bettercalendar?retryWrites=true&w=majority

**Comment by WojciechSzade** [comment]
> Co do adresów ip to jednak nieaktualne bo ustawiłem po prostu dostęp dla wszystkich adresów ip, więc z tym nie będzie problemu.  

Ok.
A jaki jest problem z bazą lokalnie/w repozytorium?

**Comment by WojciechSzade** [comment]
> Co do adresów ip to jednak nieaktualne bo ustawiłem po prostu dostęp dla wszystkich adresów ip, więc z tym nie będzie problemu.  
Ok.
A jaki jest problem z bazą lokalnie/w repozytorium?

**Comment by mateuszskoczek** [comment]
> > Co do adresów ip to jednak nieaktualne bo ustawiłem po prostu dostęp dla wszystkich adresów ip, więc z tym nie będzie problemu.
> 
> Ok. A jaki jest problem z bazą lokalnie/w repozytorium?

Masz na myśli żeby trzymać katalog z danymi MongoDB w repozytorium? W sumie można podpiąć inny katalog niż domyślny, przy uruchamianiu serwera mongo (--dbpath). Testy bazy w pipeline'ach też pewnie dałoby się jakoś ogarnąć. Tylko wydaje mi się, że zdalna baza będzie wygodniejsza. Po za tym merge'owanie zmian może być problematyczne, bo to są w dużej części pliki binarne.

Myślę, że to jest kwestia do przegadania na weekly/spotkaniu ze Szmurło. Mi się wydaje, że to średni pomysł, żeby trzymać bazę w repozytorium, ale może się mylę.

**Comment by WojciechSzade** [comment]
No z mergowaniem na 100% będzie problem.  
Dlatego myślałem, żeby po prostu co jakiś czas wrzucać "nową wersję" bazy z jakimiś danymi testowymi, a tak to mieć ją w .gitignore i tyle.  
Ale to do przegadania.

**Comment by WojciechSzade** [comment]
Closed via PR #26
