### ISSUE TITLE
Stworzyć projekt bazy danych

### ISSUE THREAD

**Issue by WojciechSzade** [Szade-Organization/BetterCalendar-API#9]
Należy stworzyć projekt bazy danych, przemyśleć jakich tabel potrzebujemy, zobaczyć jak działa MongoDB, opracować optymalne rozwiązanie.
Implementacja na poziomie tabel i relacji, bez dokładnych kolumn itp.
Najlepiej w formie jakiejś grafiki. 
Może jakieś krótkie wprowadzenie do MongoDB dla reszty zespołu?

**Comment by achilinski** [comment]
Mongo nie ma tabel ani kolumn btw

**Comment by achilinski** [comment]
Zrobimy collection user_data, dokument wygląda mniej więcej tak:
{
  "_id": {
    "$oid": "655ba43637a6d36f82478bce"
  },
  "user_name": "chilinsa",
  "e_mail": "chilinskiadam1@gmail.com",
  "categories": {
    "study": "red",
    "sports": "blue",
    "work": "pink"
  },
  "locations": {
    "home": "41.40338, 2.17403",
    "work": "69.40338, 15.17403",
    "fitness center": "59.40338, 35.17403"
  },
  "activities": [
    "gym",
    "working",
    "studying",
    "tennis"
  ],
  "time_table": {
    "need to finish project": [
      "20/11/2023 20:00, 20/11/2023 21:00",
      "home",
      "studying",
      "study"
    ],
    "going to gym": [
      "20/11/2023 21:30 20/11/2023 23:00",
      "fitness center",
      "gym",
      "sports"
    ]
  }
}
Nie widzę potrzeby relacji, może zmniejszy to miejsce zajmowane przez bazę, ale także ją spowolni, a chyba nie o to chodzi w mongo

**Comment by achilinski** [comment]
W miarę jak będziemy rozwijać naszą aplikację możemy dokładać kolejne pola, nie jest to problem w mongo, po to został stworzony ten system

**Comment by WojciechSzade** [comment]
Ok, dzięki.   
W przyszłości postarajmy się zamykać issues w następujący sposób:  
Assignee dodaje label `done - to be checked`  i przepisuje assignee na autora issue, który sprawdza i zwraca issue do poprawek lub je zamyka.
